[2023-04-17 20:23:37,521: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-04-17 20:23:37,584: INFO/MainProcess] mingle: searching for neighbors
[2023-04-17 20:23:38,169: INFO/SpawnPoolWorker-2] child process 11624 calling self.run()
[2023-04-17 20:23:38,184: INFO/SpawnPoolWorker-3] child process 10336 calling self.run()
[2023-04-17 20:23:38,184: INFO/SpawnPoolWorker-8] child process 17348 calling self.run()
[2023-04-17 20:23:38,184: INFO/SpawnPoolWorker-5] child process 12720 calling self.run()
[2023-04-17 20:23:38,200: INFO/SpawnPoolWorker-6] child process 12856 calling self.run()
[2023-04-17 20:23:38,200: INFO/SpawnPoolWorker-4] child process 14684 calling self.run()
[2023-04-17 20:23:38,216: INFO/SpawnPoolWorker-1] child process 3012 calling self.run()
[2023-04-17 20:23:38,247: INFO/SpawnPoolWorker-7] child process 17476 calling self.run()
[2023-04-17 20:23:38,646: INFO/MainProcess] mingle: sync with 1 nodes
[2023-04-17 20:23:38,646: INFO/MainProcess] mingle: sync complete
[2023-04-17 20:23:38,677: WARNING/MainProcess] C:\Users\Intiqam\Desktop\YT-Django-Docker-Compose-Celery-Redis-PostgreSQL\venv\Lib\site-packages\celery\fixups\django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-17 20:23:38,677: INFO/MainProcess] celery@Intigam ready.
[2023-04-17 20:23:42,277: INFO/SpawnPoolWorker-9] child process 14908 calling self.run()
[2023-04-17 20:26:01,643: WARNING/MainProcess] Exception ignored in atexit callback
[2023-04-17 20:26:01,643: WARNING/MainProcess] : 
[2023-04-17 20:26:01,643: WARNING/MainProcess] <function _exit_function at 0x0000019E450877E0>
[2023-04-17 20:26:01,643: WARNING/MainProcess] Traceback (most recent call last):
[2023-04-17 20:26:01,643: WARNING/MainProcess]   File "C:\Users\Intiqam\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\util.py", line 334, in _exit_function
[2023-04-17 20:26:02,149: WARNING/MainProcess]     
[2023-04-17 20:26:02,149: WARNING/MainProcess] _run_finalizers(0)
[2023-04-17 20:26:02,149: WARNING/MainProcess]   File "C:\Users\Intiqam\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\util.py", line 300, in _run_finalizers
[2023-04-17 20:26:02,149: WARNING/MainProcess]     
[2023-04-17 20:26:02,149: WARNING/MainProcess] finalizer()
[2023-04-17 20:26:02,149: WARNING/MainProcess]   File "C:\Users\Intiqam\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\util.py", line 224, in __call__
[2023-04-17 20:26:02,149: WARNING/MainProcess]     
[2023-04-17 20:26:02,149: WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess]  
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess] ^
[2023-04-17 20:26:02,149: WARNING/MainProcess]   File "C:\Users\Intiqam\Desktop\YT-Django-Docker-Compose-Celery-Redis-PostgreSQL\venv\Lib\site-packages\billiard\pool.py", line 1685, in _terminate_pool
[2023-04-17 20:26:02,392: WARNING/MainProcess]     
[2023-04-17 20:26:02,405: WARNING/MainProcess] timeout_handler.stop(TIMEOUT_MAX)
[2023-04-17 20:26:02,405: WARNING/MainProcess]   File "C:\Users\Intiqam\Desktop\YT-Django-Docker-Compose-Celery-Redis-PostgreSQL\venv\Lib\site-packages\billiard\pool.py", line 524, in stop
[2023-04-17 20:26:02,405: WARNING/MainProcess]     
[2023-04-17 20:26:02,405: WARNING/MainProcess] self.join(timeout)
[2023-04-17 20:26:02,405: WARNING/MainProcess]   File "C:\Users\Intiqam\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1116, in join
[2023-04-17 20:26:02,610: WARNING/MainProcess]     
[2023-04-17 20:26:02,610: WARNING/MainProcess] self._wait_for_tstate_lock(timeout=max(timeout, 0))
[2023-04-17 20:26:02,610: WARNING/MainProcess]   File "C:\Users\Intiqam\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1132, in _wait_for_tstate_lock
[2023-04-17 20:26:02,610: WARNING/MainProcess]     
[2023-04-17 20:26:02,610: WARNING/MainProcess] if lock.acquire(block, timeout):
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess]  
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess] ^
[2023-04-17 20:26:02,610: WARNING/MainProcess]   File "C:\Users\Intiqam\Desktop\YT-Django-Docker-Compose-Celery-Redis-PostgreSQL\venv\Lib\site-packages\celery\apps\worker.py", line 299, in _handle_request
[2023-04-17 20:26:02,641: WARNING/MainProcess]     
[2023-04-17 20:26:02,641: WARNING/MainProcess] raise exc(exitcode)
[2023-04-17 20:26:02,641: WARNING/MainProcess] celery.exceptions
[2023-04-17 20:26:02,641: WARNING/MainProcess] .
[2023-04-17 20:26:02,641: WARNING/MainProcess] WorkerTerminate
[2023-04-17 20:26:02,641: WARNING/MainProcess] : 
[2023-04-17 20:26:02,641: WARNING/MainProcess] 1
